language: node_js

node_js: '8'

cache: yarn

script:
  - npm run lint
  - npm run i18n:validate
  - npm run test -- --coverage

after_success:
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js

